name: doctor_ki_bole
description: A GPT-powered health assistant in Bangla.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  speech_to_text: ^7.1.0
  http: ^1.4.0
  sqflite: ^2.3.0
  path: ^1.9.0
  google_mlkit_text_recognition: ^0.15.0
  file_picker: ^10.2.0
  image_picker: ^1.0.7
  syncfusion_flutter_pdf: ^30.1.38
  permission_handler: ^12.0.1
  share_plus: ^7.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env