name: doctor_ki_bole
description: A GPT-powered health assistant in Bangla.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.6.0
  http: ^0.13.6
  sqflite: ^2.3.0
  path: ^1.9.0
  google_mlkit_text_recognition: ^0.10.0
  file_picker: ^6.2.1
  image_picker: ^1.0.7
  syncfusion_flutter_pdf: ^24.1.41
  permission_handler: ^11.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true